### ISSUE TITLE
YCM Error

### ISSUE THREAD

**Issue by rmenn** [codepushr/vim-go-runtime#2]
Followed instructions as per Readme. But i get this error. 

```
ycm_client_support.[so|pyd|dll] and ycm_core.[so|pyd|dll] not detected; you need to compile YCM before using it. Read the docs!
```

**Comment by rmenn** [comment]
Should be solved if 

changing line 8 to  
`./install.sh --clang-completer` 
should fix the issue. IMHO. 

Requires cmake to be installed as well.

**Comment by 0x7061** [comment]
Hm. I think `--clang-completer` is only adding support for c-style languages. It's not mandatory.

The real problem is that the plugin gets installed and the compiled modules are missing at that point of time. This is because the compiling is set up as a post hook in vim-plug.

Even after getting that error the compiling should kick off and everything should work just fine. I think you will get this only the first time. Just let the install script finish.

YCM Docs:

> YCM is a plugin with a compiled component. If you update YCM using Vundle and the ycm_support_libs library APIs have changed (happens rarely), YCM will notify you to recompile it. You should then rerun the install process.

**Comment by 0x7061** [comment]
Closing this for now.
